name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SERVICE_NAME: backend
  GCP_REGION: ${{ secrets.GCP_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: firebase
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - uses: google-github-actions/setup-gcloud@v1
      - name: Set GCP project ID
        run: |
          gcloud config set project $GCP_PROJECT_ID
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      # Build
      - name: Build backend
        run: |
          gcloud builds submit -t gcr.io/$GCP_PROJECT_ID/$GCP_SERVICE_NAME:$GITHUB_SHA
      - name: Download deps
        run: pnpm install
      - name: Build app
        run: pnpm build

      # Deploy
      - name: Deploy backend
        run: |
          gcloud run deploy $GCP_SERVICE_NAME \
          --region $GCP_REGION \
          --image gcr.io/$GCP_PROJECT_ID/$GCP_SERVICE_NAME:$GITHUB_SHA \
          --platform managed
          --allow-unauthenticated
      - name: Deploy hosting
        run: pnpm run deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          VITE_BACKEND_BASE_URL: ${{ secrets.BACKEND_BASE_URL }}
